/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gokul.optsis.dialog;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Gokul WPC
 */
public class MainWindow extends javax.swing.JFrame {
    
    private boolean menuShow = true;

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
    }
    
    
    public void changeIcon(JLabel lblImage, String path) {

        lblImage.setIcon(new ImageIcon(getClass().getResource(path)));
    }
    public void clickMenu(JPanel p1, JPanel p2, boolean bool) {
        if(bool) {
            p1.setBackground(new Color(171,186,117));
            p2.setBackground(new Color(129,152,48));                  

        } else {
            p1.setBackground(new Color(129,152,48));
            p2.setBackground(new Color(171,186,117));
        }
    }
    public void showHideMenu (JPanel menushowhide, boolean show) {
        if(show) {
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
             menuShow = false;
        } else {
            menushowhide.setPreferredSize(new Dimension(55, menushowhide.getHeight())); 
             menuShow = true;
        }
        SwingUtilities.updateComponentTreeUI(this);
    }
    
    
    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlMainMenu = new javax.swing.JPanel();
        pnlMenuIcon = new javax.swing.JPanel();
        pnlLineList = new javax.swing.JPanel();
        pnlIconList = new javax.swing.JPanel();
        lblIconList = new javax.swing.JLabel();
        pnlIconSetting = new javax.swing.JPanel();
        lblIconSettings = new javax.swing.JLabel();
        pnlLineSettings = new javax.swing.JPanel();
        pnlMenuShow = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        pnlMainDashboard = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlSelect = new javax.swing.JPanel();
        pnlShow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainHeader.setBackground(new java.awt.Color(129, 152, 48));
        pnlMainHeader.setPreferredSize(new java.awt.Dimension(800, 50));
        pnlMainHeader.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        lblTitle.setText("OptSis");
        lblTitle.setPreferredSize(new java.awt.Dimension(200, 17));
        pnlMainHeader.add(lblTitle, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnlMainHeader, java.awt.BorderLayout.PAGE_START);

        pnlMainMenu.setBackground(new java.awt.Color(129, 152, 48));
        pnlMainMenu.setPreferredSize(new java.awt.Dimension(50, 450));
        pnlMainMenu.setLayout(new java.awt.BorderLayout());

        pnlMenuIcon.setBackground(new java.awt.Color(129, 152, 48));
        pnlMenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLineList.setBackground(new java.awt.Color(129, 152, 48));
        pnlLineList.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout pnlLineListLayout = new javax.swing.GroupLayout(pnlLineList);
        pnlLineList.setLayout(pnlLineListLayout);
        pnlLineListLayout.setHorizontalGroup(
            pnlLineListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlLineListLayout.setVerticalGroup(
            pnlLineListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnlMenuIcon.add(pnlLineList, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 10, -1, 5));

        pnlIconList.setBackground(new java.awt.Color(129, 152, 48));
        pnlIconList.setPreferredSize(new java.awt.Dimension(40, 40));

        lblIconList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        lblIconList.setPreferredSize(new java.awt.Dimension(40, 40));
        lblIconList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconListMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlIconListLayout = new javax.swing.GroupLayout(pnlIconList);
        pnlIconList.setLayout(pnlIconListLayout);
        pnlIconListLayout.setHorizontalGroup(
            pnlIconListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIconListLayout.createSequentialGroup()
                .addComponent(lblIconList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlIconListLayout.setVerticalGroup(
            pnlIconListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIconListLayout.createSequentialGroup()
                .addComponent(lblIconList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenuIcon.add(pnlIconList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pnlIconSetting.setBackground(new java.awt.Color(129, 152, 48));
        pnlIconSetting.setPreferredSize(new java.awt.Dimension(40, 40));

        lblIconSettings.setBackground(new java.awt.Color(129, 152, 48));
        lblIconSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        lblIconSettings.setToolTipText("");
        lblIconSettings.setPreferredSize(new java.awt.Dimension(40, 40));
        lblIconSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconSettingsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlIconSettingLayout = new javax.swing.GroupLayout(pnlIconSetting);
        pnlIconSetting.setLayout(pnlIconSettingLayout);
        pnlIconSettingLayout.setHorizontalGroup(
            pnlIconSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIconSettingLayout.createSequentialGroup()
                .addComponent(lblIconSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlIconSettingLayout.setVerticalGroup(
            pnlIconSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIconSettingLayout.createSequentialGroup()
                .addComponent(lblIconSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenuIcon.add(pnlIconSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        pnlLineSettings.setBackground(new java.awt.Color(129, 152, 48));
        pnlLineSettings.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout pnlLineSettingsLayout = new javax.swing.GroupLayout(pnlLineSettings);
        pnlLineSettings.setLayout(pnlLineSettingsLayout);
        pnlLineSettingsLayout.setHorizontalGroup(
            pnlLineSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlLineSettingsLayout.setVerticalGroup(
            pnlLineSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnlMenuIcon.add(pnlLineSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 80, -1, 5));

        pnlMainMenu.add(pnlMenuIcon, java.awt.BorderLayout.LINE_START);

        pnlMenuShow.setBackground(new java.awt.Color(171, 186, 117));
        pnlMenuShow.setPreferredSize(new java.awt.Dimension(179, 450));
        pnlMenuShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        pnlMenuShow.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, -1));

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        pnlMenuShow.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, -1));

        btnSelect.setText("Select");
        btnSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectMouseClicked(evt);
            }
        });
        pnlMenuShow.add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, -1));

        btnShow.setText("Show");
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMouseClicked(evt);
            }
        });
        pnlMenuShow.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, -1));

        pnlMainMenu.add(pnlMenuShow, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMainMenu, java.awt.BorderLayout.LINE_START);

        pnlMainDashboard.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pnlMainDashboard.add(pnlHome, "card2");

        pnlSelect.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout pnlSelectLayout = new javax.swing.GroupLayout(pnlSelect);
        pnlSelect.setLayout(pnlSelectLayout);
        pnlSelectLayout.setHorizontalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        pnlSelectLayout.setVerticalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pnlMainDashboard.add(pnlSelect, "card3");

        javax.swing.GroupLayout pnlShowLayout = new javax.swing.GroupLayout(pnlShow);
        pnlShow.setLayout(pnlShowLayout);
        pnlShowLayout.setHorizontalGroup(
            pnlShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        pnlShowLayout.setVerticalGroup(
            pnlShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pnlMainDashboard.add(pnlShow, "card4");

        getContentPane().add(pnlMainDashboard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseClicked
        showHideMenu(pnlMainMenu, menuShow);

        if(menuShow) {
            changeIcon(lblIconList, "/images/list.png");
        } else {
            changeIcon(lblIconList, "/images/left.png");
        }
    }//GEN-LAST:event_lblIconListMouseClicked

    private void lblIconListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseEntered
//        changeColor(pnlIconList, new Color(171, 186, 117)); 
        changeColor(pnlLineList, new Color(204, 0, 0)); 
    }//GEN-LAST:event_lblIconListMouseEntered

    private void lblIconListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseExited
//       changeColor(pnlIconList, new Color(129, 152, 48)); 
       changeColor(pnlLineList, new Color(129, 152, 48)); 
    }//GEN-LAST:event_lblIconListMouseExited

    private void lblIconSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSettingsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconSettingsMouseClicked

    private void lblIconSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSettingsMouseEntered
//       changeColor(pnlIconSetting, new Color(171, 186, 117)); 
       changeColor(pnlLineSettings, new Color(204, 0, 0)); 
    }//GEN-LAST:event_lblIconSettingsMouseEntered

    private void lblIconSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSettingsMouseExited
//        changeColor(pnlIconSetting, new Color(129, 152, 48));
        changeColor(pnlLineSettings, new Color(129, 152, 48)); 
    }//GEN-LAST:event_lblIconSettingsMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        pnlMainDashboard.removeAll();
        pnlMainDashboard.add(pnlHome);
        
        showHideMenu(pnlMainMenu,  Boolean.FALSE);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectMouseClicked
        pnlMainDashboard.removeAll();
        pnlMainDashboard.add(pnlSelect);
        
        showHideMenu(pnlMainMenu,  Boolean.FALSE);
    }//GEN-LAST:event_btnSelectMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        pnlMainDashboard.removeAll();
        pnlMainDashboard.add(pnlShow);
        
        showHideMenu(pnlMainMenu,  Boolean.FALSE);
        
        AddNew andialog = new AddNew(this, true);
        andialog.setLocationRelativeTo(null);
        andialog.setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMouseClicked
        pnlMainDashboard.removeAll();
        pnlMainDashboard.add(pnlShow);
        
        showHideMenu(pnlMainMenu,  Boolean.FALSE);      // TODO add your handling code here:
    }//GEN-LAST:event_btnShowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel lblIconList;
    private javax.swing.JLabel lblIconSettings;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlIconList;
    private javax.swing.JPanel pnlIconSetting;
    private javax.swing.JPanel pnlLineList;
    private javax.swing.JPanel pnlLineSettings;
    private javax.swing.JPanel pnlMainDashboard;
    private javax.swing.JPanel pnlMainHeader;
    private javax.swing.JPanel pnlMainMenu;
    private javax.swing.JPanel pnlMenuIcon;
    private javax.swing.JPanel pnlMenuShow;
    private javax.swing.JPanel pnlSelect;
    private javax.swing.JPanel pnlShow;
    // End of variables declaration//GEN-END:variables

}
