/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gokul.optsis;

import com.gokul.optsis.backtest.StrgBackTestPanel;
import com.gokul.optsis.panel.StrgShowPanel;
import com.gokul.optsis.dialog.AddNew;
import com.gokul.optsis.dialog.StrategyListDialog;
import com.gokul.optsis.model.OptionStrategy;
import com.gokul.optsis.model.StrgSetting;
import com.gokul.optsis.util.Util;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;


/**
 *
 * @author Gokul WPC
 */
public class MainWindow extends javax.swing.JFrame {
    
    private boolean menuShow = true;
    private String strStgName = "Current Strategy: Not Selected  ";
    private String strStgPL = "Current P/L        :";
    private OptionStrategy objOptionStrategy;
    private StrgSetting strgSetting;
    private StrgShowPanel stgyShowPanel;
    private StrgSettingPanel strgSettingPanel;
    private StrgBackTestPanel strgBackTestPanel;
    

    

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        
        //If not exist create new tables.
        Util.createNewStrategyTable();
        Util.createNewStrategySettingTable();
        
        //Get Strgsetting data
        strgSetting = Util.getStrgSettingData();
        
    }
    
    public StrgSetting getStrgSetting() {
        return this.strgSetting;
    }
    
    public void setStrgSetting(StrgSetting obj) {
        this.strgSetting = obj;
        objOptionStrategy.setChartSetting(obj.getChartStart(), obj.getChartEnd());
    }
    
    public void updatePosition() {
       selectStrategy(strgSetting);
       showStgyPanel();
    }
    
    public void setCurrentStrategy(OptionStrategy obj) {
        this.objOptionStrategy = obj;
    }
 
    public void selectStrategy(StrgSetting setting) {
        strgSetting = setting;
        strStgName = strgSetting.getName();
        this.objOptionStrategy = Util.getOptionStrategyData(strStgName);
        this.objOptionStrategy.setChartSetting(strgSetting.getChartStart(), strgSetting.getChartEnd());
        
        lblCurrentStgName.setText("Current Strategy: " + strStgName + "   ");
        lblCurrentStgPL.setText("Current P/L        : " + objOptionStrategy.getPL());
              
    }
    
    public OptionStrategy getCurrentStrategy() {
        return this.objOptionStrategy;
    }
    
    public void changeIcon(JLabel lblImage, String path) {

        lblImage.setIcon(new ImageIcon(getClass().getResource(path)));
    }
    public void clickMenu(JPanel p1, JPanel p2, boolean bool) {
        if(bool) {
            p1.setBackground(new Color(171,186,117));
            p2.setBackground(new Color(129,152,48));                  

        } else {
            p1.setBackground(new Color(129,152,48));
            p2.setBackground(new Color(171,186,117));
        }
    }
    public void showHideMenu (JPanel menushowhide, boolean show) {
        if(show) {
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
             menuShow = false;
        } else {
            menushowhide.setPreferredSize(new Dimension(55, menushowhide.getHeight())); 
             menuShow = true;
        }
        SwingUtilities.updateComponentTreeUI(this);
    }
    
    
    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCurrentStgName = new javax.swing.JLabel();
        lblCurrentStgPL = new javax.swing.JLabel();
        pnlMainMenu = new javax.swing.JPanel();
        pnlMenuIcon = new javax.swing.JPanel();
        pnlLineList = new javax.swing.JPanel();
        pnlIconList = new javax.swing.JPanel();
        lblIconList = new javax.swing.JLabel();
        pnlIconSetting = new javax.swing.JPanel();
        lblIconSettings = new javax.swing.JLabel();
        pnlLineSettings = new javax.swing.JPanel();
        btnBackTest = new javax.swing.JButton();
        pnlMenuShow = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        pnlMainDashboard = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlSelect = new javax.swing.JPanel();
        pnlShow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        pnlMainHeader.setBackground(new java.awt.Color(129, 152, 48));
        pnlMainHeader.setPreferredSize(new java.awt.Dimension(800, 50));
        pnlMainHeader.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(192, 204, 153));
        lblTitle.setText("OptSis");
        lblTitle.setPreferredSize(new java.awt.Dimension(200, 17));
        pnlMainHeader.add(lblTitle, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(129, 152, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 50));

        lblCurrentStgName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCurrentStgName.setText("Current Strategy: Not Selected");

        lblCurrentStgPL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCurrentStgPL.setText("Current P/L         :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentStgName, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentStgPL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentStgName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCurrentStgPL)
                .addContainerGap())
        );

        pnlMainHeader.add(jPanel1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlMainHeader, java.awt.BorderLayout.PAGE_START);

        pnlMainMenu.setBackground(new java.awt.Color(129, 152, 48));
        pnlMainMenu.setPreferredSize(new java.awt.Dimension(50, 450));
        pnlMainMenu.setLayout(new java.awt.BorderLayout());

        pnlMenuIcon.setBackground(new java.awt.Color(129, 152, 48));
        pnlMenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLineList.setBackground(new java.awt.Color(129, 152, 48));
        pnlLineList.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout pnlLineListLayout = new javax.swing.GroupLayout(pnlLineList);
        pnlLineList.setLayout(pnlLineListLayout);
        pnlLineListLayout.setHorizontalGroup(
            pnlLineListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlLineListLayout.setVerticalGroup(
            pnlLineListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnlMenuIcon.add(pnlLineList, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 10, -1, 5));

        pnlIconList.setBackground(new java.awt.Color(129, 152, 48));
        pnlIconList.setPreferredSize(new java.awt.Dimension(40, 40));

        lblIconList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        lblIconList.setAlignmentY(0.0F);
        lblIconList.setPreferredSize(new java.awt.Dimension(40, 40));
        lblIconList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconListMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlIconListLayout = new javax.swing.GroupLayout(pnlIconList);
        pnlIconList.setLayout(pnlIconListLayout);
        pnlIconListLayout.setHorizontalGroup(
            pnlIconListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIconListLayout.createSequentialGroup()
                .addComponent(lblIconList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlIconListLayout.setVerticalGroup(
            pnlIconListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIconListLayout.createSequentialGroup()
                .addComponent(lblIconList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenuIcon.add(pnlIconList, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, -1));

        pnlIconSetting.setBackground(new java.awt.Color(129, 152, 48));
        pnlIconSetting.setPreferredSize(new java.awt.Dimension(40, 40));

        lblIconSettings.setBackground(new java.awt.Color(129, 152, 48));
        lblIconSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        lblIconSettings.setToolTipText("");
        lblIconSettings.setAlignmentY(0.0F);
        lblIconSettings.setPreferredSize(new java.awt.Dimension(40, 40));
        lblIconSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconSettingsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlIconSettingLayout = new javax.swing.GroupLayout(pnlIconSetting);
        pnlIconSetting.setLayout(pnlIconSettingLayout);
        pnlIconSettingLayout.setHorizontalGroup(
            pnlIconSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIconSettingLayout.createSequentialGroup()
                .addComponent(lblIconSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlIconSettingLayout.setVerticalGroup(
            pnlIconSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIconSettingLayout.createSequentialGroup()
                .addComponent(lblIconSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenuIcon.add(pnlIconSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, -1, -1));

        pnlLineSettings.setBackground(new java.awt.Color(129, 152, 48));
        pnlLineSettings.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout pnlLineSettingsLayout = new javax.swing.GroupLayout(pnlLineSettings);
        pnlLineSettings.setLayout(pnlLineSettingsLayout);
        pnlLineSettingsLayout.setHorizontalGroup(
            pnlLineSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlLineSettingsLayout.setVerticalGroup(
            pnlLineSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnlMenuIcon.add(pnlLineSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 80, -1, 5));

        btnBackTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_science_application_50px.png"))); // NOI18N
        btnBackTest.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBackTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackTestMouseClicked(evt);
            }
        });
        pnlMenuIcon.add(btnBackTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        pnlMainMenu.add(pnlMenuIcon, java.awt.BorderLayout.LINE_START);

        pnlMenuShow.setBackground(new java.awt.Color(171, 186, 117));
        pnlMenuShow.setPreferredSize(new java.awt.Dimension(179, 450));
        pnlMenuShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_home_20px.png"))); // NOI18N
        btnHome.setMnemonic('H');
        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        pnlMenuShow.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, -1));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_database_20px.png"))); // NOI18N
        btnAdd.setMnemonic('A');
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        pnlMenuShow.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, -1));

        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_select_20px.png"))); // NOI18N
        btnSelect.setMnemonic('e');
        btnSelect.setText("Select");
        btnSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectMouseClicked(evt);
            }
        });
        pnlMenuShow.add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, -1));

        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_showing_video_frames_20px.png"))); // NOI18N
        btnShow.setMnemonic('S');
        btnShow.setText("Show");
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMouseClicked(evt);
            }
        });
        pnlMenuShow.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, -1));

        pnlMainMenu.add(pnlMenuShow, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMainMenu, java.awt.BorderLayout.LINE_START);

        pnlMainDashboard.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        pnlMainDashboard.add(pnlHome, "card2");

        pnlSelect.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout pnlSelectLayout = new javax.swing.GroupLayout(pnlSelect);
        pnlSelect.setLayout(pnlSelectLayout);
        pnlSelectLayout.setHorizontalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnlSelectLayout.setVerticalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        pnlMainDashboard.add(pnlSelect, "card3");

        pnlShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlMainDashboard.add(pnlShow, "card4");

        getContentPane().add(pnlMainDashboard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseClicked
        showHideMenu(pnlMainMenu, menuShow);

        if(menuShow) {
            changeIcon(lblIconList, "/images/list.png");
        } else {
            changeIcon(lblIconList, "/images/left.png");
        }
    }//GEN-LAST:event_lblIconListMouseClicked

    private void lblIconListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseEntered
        changeColor(pnlLineList, new Color(204, 0, 0)); 
    }//GEN-LAST:event_lblIconListMouseEntered

    private void lblIconListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseExited
       changeColor(pnlLineList, new Color(129, 152, 48)); 
    }//GEN-LAST:event_lblIconListMouseExited

    private void lblIconSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSettingsMouseClicked
        showStrgSettingPanel();
    }//GEN-LAST:event_lblIconSettingsMouseClicked

    private void lblIconSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSettingsMouseEntered
       changeColor(pnlLineSettings, new Color(204, 0, 0)); 
    }//GEN-LAST:event_lblIconSettingsMouseEntered

    private void lblIconSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSettingsMouseExited
        changeColor(pnlLineSettings, new Color(129, 152, 48)); 
    }//GEN-LAST:event_lblIconSettingsMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        showHomePanel();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectMouseClicked
        pnlMainDashboard.removeAll();
        pnlMainDashboard.add(pnlSelect);
        
        strgSetting = Util.getStrgSettingData(); // Get StrgSetting data from database.
        
        showHideMenu(pnlMainMenu,  Boolean.FALSE);
        StrategyListDialog stgListDiag = new StrategyListDialog(this, true, this);
        stgListDiag.setLocationRelativeTo(null);
        stgListDiag.setVisible(true);       
    }//GEN-LAST:event_btnSelectMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
       
        showHideMenu(pnlMainMenu,  Boolean.FALSE);
        
        AddNew andialog = new AddNew(this, true, this);
        andialog.setLocationRelativeTo(null);
        andialog.setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMouseClicked
        showStgyPanel();
    }//GEN-LAST:event_btnShowMouseClicked

    private void btnBackTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackTestMouseClicked
       showStrgBackTestPanel(); 
    }//GEN-LAST:event_btnBackTestMouseClicked

    private void showStrgBackTestPanel() {
        pnlMainDashboard.removeAll();
        strgBackTestPanel = new StrgBackTestPanel(this);
        pnlMainDashboard.add(strgBackTestPanel);  
        
        SwingUtilities.updateComponentTreeUI(this);        
    }
    private void showStrgSettingPanel() {
        pnlMainDashboard.removeAll();
        strgSettingPanel = new StrgSettingPanel( this );
        pnlMainDashboard.add(strgSettingPanel);  
        
        SwingUtilities.updateComponentTreeUI(this);
    }
    private void showHomePanel() {
        pnlMainDashboard.removeAll();
        pnlMainDashboard.add(pnlHome);
        
        showHideMenu(pnlMainMenu,  Boolean.FALSE);       
    }
    
    private void showStgyPanel() {
       
        pnlMainDashboard.removeAll();
        stgyShowPanel = new StrgShowPanel( this );
        pnlMainDashboard.add(stgyShowPanel);
        
        showHideMenu(pnlMainMenu,  Boolean.FALSE);  
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackTest;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnShow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCurrentStgName;
    private javax.swing.JLabel lblCurrentStgPL;
    private javax.swing.JLabel lblIconList;
    private javax.swing.JLabel lblIconSettings;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlIconList;
    private javax.swing.JPanel pnlIconSetting;
    private javax.swing.JPanel pnlLineList;
    private javax.swing.JPanel pnlLineSettings;
    private javax.swing.JPanel pnlMainDashboard;
    private javax.swing.JPanel pnlMainHeader;
    private javax.swing.JPanel pnlMainMenu;
    private javax.swing.JPanel pnlMenuIcon;
    private javax.swing.JPanel pnlMenuShow;
    private javax.swing.JPanel pnlSelect;
    private javax.swing.JPanel pnlShow;
    // End of variables declaration//GEN-END:variables

}
