/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gokul.optsis.backtest.dialog;

import com.gokul.optsis.MainWindow;
import com.gokul.optsis.backtest.model.OptLeg;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Gokul WPC
 */
public class AddNewLegDialog extends javax.swing.JDialog {
    
     private Connection connection = null;
     private MainWindow mainWindow;
     private OptLeg objOptLeg;
     

    /**
     * Creates new form AddNewLegDialog
     */
    public AddNewLegDialog(java.awt.Frame parent, boolean modal, MainWindow window) {
        super(parent, modal);
        this.mainWindow = window;
       
        initComponents();
        
        txtStgName.setText("BackTest");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpType = new javax.swing.ButtonGroup();
        btnGrpPosition = new javax.swing.ButtonGroup();
        pnlHeader = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStgName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStgStrike = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStgPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStgSymbol = new javax.swing.JTextField();
        dtpStgExpiry = new com.toedter.calendar.JDateChooser();
        rdbtnCall = new javax.swing.JRadioButton();
        rdbtnPut = new javax.swing.JRadioButton();
        rdbtnLong = new javax.swing.JRadioButton();
        rdbtnShort = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Strategy Add New Leg");

        pnlHeader.setBackground(new java.awt.Color(129, 152, 48));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Strategy Name");
        pnlMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        txtStgName.setEnabled(false);
        pnlMain.add(txtStgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Expiry");
        pnlMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Type");
        pnlMain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Strike");
        pnlMain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        pnlMain.add(txtStgStrike, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Position");
        pnlMain.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtStgPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStgPriceFocusGained(evt);
            }
        });
        pnlMain.add(txtStgPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Price");
        pnlMain.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Symbol");
        pnlMain.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txtStgSymbol.setEnabled(false);
        pnlMain.add(txtStgSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 150, -1));
        pnlMain.add(dtpStgExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 150, -1));

        btnGrpType.add(rdbtnCall);
        rdbtnCall.setSelected(true);
        rdbtnCall.setText("Call");
        pnlMain.add(rdbtnCall, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        btnGrpType.add(rdbtnPut);
        rdbtnPut.setText("Put");
        pnlMain.add(rdbtnPut, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        btnGrpPosition.add(rdbtnLong);
        rdbtnLong.setSelected(true);
        rdbtnLong.setText("Long");
        pnlMain.add(rdbtnLong, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        btnGrpPosition.add(rdbtnShort);
        rdbtnShort.setText("Short");
        pnlMain.add(rdbtnShort, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        pnlMain.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        btnClose.setText("Close");
        btnClose.setPreferredSize(new java.awt.Dimension(100, 25));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        pnlMain.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jPanel1.setBackground(new java.awt.Color(129, 152, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 400, 40));

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
       
        objOptLeg = new OptLeg();
        
        objOptLeg.setStrategyName(txtStgName.getText());
        objOptLeg.setSymbol(txtStgSymbol.getText());
        objOptLeg.setPosition(rdbtnLong.isSelected());
        objOptLeg.setPrice(Float.parseFloat(txtStgPrice.getText()));

        PreparedStatement stmt = null;
        int nColumnCnt = 4; //

        String insert_into_strategy = "insert into STRGTEST (name, symbol, position, price, covered, coverprice)values ( ?, ?, ?, ?, false, 0)";

        try {
                Class.forName("org.h2.Driver");
                connection = DriverManager.getConnection("jdbc:h2:tcp://localhost/~/test", "sa", "");
                stmt = connection.prepareStatement(insert_into_strategy);
                stmt.setString(1, txtStgName.getText());
                stmt.setString(2, txtStgSymbol.getText());
                stmt.setBoolean( 3, rdbtnLong.isSelected());


                stmt.setInt( 4, Integer.parseInt(txtStgPrice.getText()));

                if (stmt.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(null, "New Strategy name inserted into table");
                        Object rowData[] = new Object[nColumnCnt] ;
                        rowData[0] = txtStgName.getText();
                        rowData[1] = txtStgSymbol.getText();
                        rowData[2] = rdbtnLong.isSelected();
                        rowData[3] = Float.parseFloat(txtStgPrice.getText());

                        System.out.print(rowData.toString());

                }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("SQLException: " + ex.getMessage());
//            System.out.println("SQLState: " + ex.);
//            System.out.println("VendorError: " + ex.getErrorCode());
            ex.printStackTrace();
        } 
        finally {
            // it is a good idea to release
            // resources in a finally{} block
            // in reverse-order of their creation
            // if they are no-longer needed
//
//            if (rs != null) {
//                try {
//                    rs.close();
//                } catch (SQLException sqlEx) { } // ignore
//
//                rs = null;
//            }

            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException sqlEx) { } // ignore

                stmt = null;
            }
        }
//        mainWindow.updatePosition();
        
			
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
       dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void txtStgPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStgPriceFocusGained
      		        SimpleDateFormat sdf = new SimpleDateFormat("yyddMMM");
		        String date = sdf.format(dtpStgExpiry.getDate());
		        date = "NIFTY" + date.toUpperCase() + txtStgStrike.getText();
		        if( rdbtnCall.isSelected()) {
		        	date = date + "CE";
		        } else {
		        	date = date + "PE";
		        }

		        txtStgSymbol.setText(date);
    }//GEN-LAST:event_txtStgPriceFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.ButtonGroup btnGrpPosition;
    private javax.swing.ButtonGroup btnGrpType;
    private com.toedter.calendar.JDateChooser dtpStgExpiry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JRadioButton rdbtnCall;
    private javax.swing.JRadioButton rdbtnLong;
    private javax.swing.JRadioButton rdbtnPut;
    private javax.swing.JRadioButton rdbtnShort;
    private javax.swing.JTextField txtStgName;
    private javax.swing.JTextField txtStgPrice;
    private javax.swing.JTextField txtStgStrike;
    private javax.swing.JTextField txtStgSymbol;
    // End of variables declaration//GEN-END:variables
}
